---
title: "RNA_seq_analysis_part2"
author: "Sobur"
date: "2024-06-24"

---

## Import required libraries
```{r}
library(tidyverse)
library(DESeq2)
```

### Import Count data from data dirctory
```{r}
count_data <- read.delim("data/counts_matrix.csv", header = TRUE, row.names = 1, sep = ",")
```

### For the convenience of DESeq2 analysis, remove the GeneSymbol Column for now
```{r}
count_data <- select(count_data, -GeneSymbol)
```

## Remove low read count rows
```{r}
count_data <- count_data[rowSums(count_data) > 50, ]
```

##Create a metadata of tissue
```{r}
tissue <- factor(c(rep("Blood", 4), rep("Fat", 2), rep("IEL", 3), rep("Kidney", 3),
                rep("Liver", 2), rep("SG", 3), rep("Spleen", 5)))
coldata <- data.frame(row.names = colnames(count_data), tissue)
```


```{r}
dds <- DESeqDataSetFromMatrix(countData = count_data,
                              colData = coldata,
                              design = ~ tissue) # design is the column name in the coldata with condition or for here tissue type
```


```{r}
dds <- DESeq(dds)
```
```{r}
contrast_BI <- c("tissue", "Blood", "IEL")
```

```{r}
res <- results(dds, contrast=contrast_BI)
```

```{r}
plotMA(res, ylim=c(-2,2))
```



```{r}
sigs <- na.omit(res)

```


```{r}
sigs <- sigs[sigs$padj < 0.05,]
```

```{r}
sigs <- sigs[sigs$log2FoldChange > 1,]
```

Convert Ensembl IDs to genesymbol
org.Mm.eg.db: Genome wide annotation for Mouse. R package version 3.8.2.

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("org.Mm.eg.db")
BiocManager::install("AnnotationDbi")
BiocManager::install("EnhancedVolcano")
```

```{r}
library(org.Mm.eg.db)
library(AnnotationDbi)
library(EnhancedVolcano)
```


```{r}
sign_data <- as.data.frame(sigs)
```

Conversion


```{r}
# Remove version numbers from Ensembl IDs
clean_ensembl_ids <- sub("\\..*", "", rownames(sign_data))

```


```{r}
# Map cleaned Ensembl IDs to Gene Symbols
gene_symbols <- mapIds(org.Mm.eg.db, 
                       keys = clean_ensembl_ids, 
                       column = "SYMBOL", 
                       keytype = "ENSEMBL", 
                       multiVals = "first")


```


```{r}
# Add the Gene Symbols to your data frame
sign_data$GeneSymbol <- gene_symbols
```

Gene ontology (GO)

```{r}
BiocManager::install("clusterProfiler")

```

```{r}
library(clusterProfiler)
```

```{r}
gene_annotation <- enrichGO(gene = clean_ensembl_ids, OrgDb = "org.Mm.eg.db", keyType = "ENSEMBL", ont = "BP")

```

```{r}
as.data.frame(gene_annotation)
```



```{r}
GO_plot <- plot(barplot(gene_annotation, showCategory = 20))
png("out.png", res = 250, width = 2200, height = 3000)
print(GO_plot)
dev.off()
```
```{r}
sigs_E <- na.omit(res)
```

```{r}
sign_Edata <- as.data.frame(sigs_E)
```

```{r}
# Remove version numbers from Ensembl IDs
clean_ensembl_ids_E <- sub("\\..*", "", rownames(sign_Edata))

```


```{r}
# Map cleaned Ensembl IDs to Gene Symbols
gene_symbols_E <- mapIds(org.Mm.eg.db, 
                       keys = clean_ensembl_ids_E, 
                       column = "SYMBOL", 
                       keytype = "ENSEMBL", 
                       multiVals = "first")


```


```{r}
# Add the Gene Symbols to your data frame
sign_Edata$GeneSymbol <- gene_symbols_E
```

```{r}
vol_plot <- EnhancedVolcano(sign_Edata,
                x = "log2FoldChange",
                y = "padj",
                lab = sign_Edata$GeneSymbol,
                pCutoff = 10e-25,
                FCcutoff = 2.5,
                pointSize = 4.0,
                labSize = 6.0,
                colAlpha = 1,
                legendLabels=c('Not sig.','Log (base 2) FC','p-value','p-value & Log (base 2) FC'),
                legendPosition = 'top',
                legendLabSize = 16,
                legendIconSize = 5.0)
vol_plot
png("volcano_plot.png", res = 250, width = 2200, height = 3000)
print(vol_plot)
dev.off()
```


